version: '3'
services:
    uashield:
      image: ghcr.io/wolfunita/wolfshield:master
      restart: always
      environment:
        WORKERS: '256'
        USEPROXY: 'false'
      deploy:
        replicas: 3

