name: Node CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Windows 64bit and 32bit 
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T win
